version: '3.8'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile 
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: ama
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  laravel:

volumes:
  mysql_data:
